version: "3.8"
services:
  webapicarbrands:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=CarBrandsDB;Username=postgres;Password=mysecretpassword

  db:
    image: postgres:17.3
    restart: always
    environment:
      POSTGRES_DB: CarBrandsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
